CREATE TABLE IF NOT EXISTS post_metrics (
  category_id TEXT NOT NULL,
  post_id TEXT NOT NULL,
  views INTEGER NOT NULL DEFAULT 0,
  likes INTEGER NOT NULL DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (category_id, post_id)
);
